apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: x2srgpzbp-go 
  janus-idp.io/tekton: x2srgpzbp-go
  backstage.io/kubernetes-id: x2srgpzbp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x2srgpzbp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml