apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x2srgpzbp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x2srgpzbp-go 
  name: x2srgpzbp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: x2srgpzbp-go 
